
cat <<EOF>> docker-compose.yaml
services:
###############  MASTER  #########
  mysql-master:
    image: mysql:8
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/my.conf:/my.cnf:ro
    command: >
      bash -c "
      cp /my.cnf /etc/mysql/conf.d/
      &&chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    ports:
    - 3306:3306
EOF

cat <<EOF>> docker-compose.yaml
services:
###############  SLAVE  #########
  mysql-slave:
    image: mysql:8
    restart: always
    volumes: 
      - ./slave/data:/var/lib/mysql
      - ./slave/my.conf:/my.cnf:ro
    command: >
      bash -c "
      cp /my.cnf /etc/mysql/conf.d/
      &&chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
      
EOF
